spring:
  application:
    name: spring-cloud-eureka-consumer-hystrix

server:
  port: 2223

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

feign:
  hystrix:
    enabled: true
