server:
    port: 8882
    address: 0.0.0.0
    servlet:
        context-path: /account-service

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/tcc_account?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
    application:
        name: account-service

hmily:
    tcc:
        serializer: kryo
        recoverDelayTime: 128
        retryMax: 30
        scheduledDelay: 128
        scheduledThreadMax:  10
        repositorySupport: db
        tccDbConfig:
            driverClassName: com.mysql.jdbc.Driver
            url:  jdbc:mysql://127.0.0.1:3306/tcc?useUnicode=true&characterEncoding=utf8&useSSL=false
            username: root
            password: 123456

mybatis:
    type-aliases-package: com.gsq.learning.tcc.account.entity
    config-location: classpath:mybatis/mybatis-config.xml

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/
    instance:
        prefer-ip-address: true

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.hmily.tcc.bonuspoint: debug
        com.hmily.tcc.lottery: debug
        com.hmily.tcc: debug
        io.netty: info
    path: "./logs"

